### PR TITLE
Improved readability of example code in README.md

### PR DESCRIPTION
**Pull request by DrOfAwesomeness**
I've improved the readability of the example code because I had issues reading it when I first looked at remotestorage-server. I also added a couple of comments briefly explaining what tokenStore and dataStore do (to me it was self-explanatory, but it might not be to everyone).

### CODE REVIEW

**Comment by skddc** [comment]
Oops. Missed this PR somehow.

@DrOfAwesomeness Are you currently using or hacking on this software/code?

**Comment by DrOfAwesomeness** [comment]
@skddc Thanks for the offer, but I haven't really used this much since I opened this PR.

**Comment by skddc** [comment]
Alright, cool.

However, do you think it would still improve the README? I could merge it then.

**Comment by DrOfAwesomeness** [comment]
I think it would, actually, since it looks like the README hasn't changed.

**Comment by raucao** [comment]
Great, thanks! :)

**Pull request merged**
